#
# Copyright (c) 2015 University of Cambridge
# All rights reserved.
#
#
#  File:
#        crypto_regs_defines.tcl
#
#  Description:
#        This file is automatically generated with tcl defines for the software
#
# This software was developed by the University of Cambridge Computer Laboratory 
# under EPSRC INTERNET Project EP/H040536/1, National Science Foundation under Grant No. CNS-0855268,
# and Defense Advanced Research Projects Agency (DARPA) and Air Force Research Laboratory (AFRL),
# under contract FA8750-11-C-0249.
#
# @NETFPGA_LICENSE_HEADER_START@
#
# Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for
# additional information regarding copyright ownership.  NetFPGA licenses this
# file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#   http://netfpga-cic.org
#
# Unless required by applicable law or agreed to in writing, Work distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
# @NETFPGA_LICENSE_HEADER_END@
#

set CRYPTO_REGS_ID_0_OFFSET 0x0
set CRYPTO_REGS_ID_0_DEFAULT 0x000000C2
set CRYPTO_REGS_ID_0_WIDTH 32
set CRYPTO_REGS_VERSION_0_OFFSET 0x4
set CRYPTO_REGS_VERSION_0_DEFAULT 0x1
set CRYPTO_REGS_VERSION_0_WIDTH 32
set CRYPTO_REGS_RESET_0_OFFSET 0x8
set CRYPTO_REGS_RESET_0_DEFAULT 0x0
set CRYPTO_REGS_RESET_0_WIDTH 16
set CRYPTO_REGS_FLIP_0_OFFSET 0xC
set CRYPTO_REGS_FLIP_0_DEFAULT 0x0
set CRYPTO_REGS_FLIP_0_WIDTH 32
set CRYPTO_REGS_DEBUG_0_OFFSET 0x10
set CRYPTO_REGS_DEBUG_0_DEFAULT 0x0
set CRYPTO_REGS_DEBUG_0_WIDTH 32
set CRYPTO_REGS_PKTIN_0_OFFSET 0x14
set CRYPTO_REGS_PKTIN_0_DEFAULT 0x0
set CRYPTO_REGS_PKTIN_0_WIDTH 32
set CRYPTO_REGS_PKTOUT_0_OFFSET 0x18
set CRYPTO_REGS_PKTOUT_0_DEFAULT 0x0
set CRYPTO_REGS_PKTOUT_0_WIDTH 32
set CRYPTO_REGS_KEY_0_OFFSET 0x1C
set CRYPTO_REGS_KEY_0_DEFAULT 0x0
set CRYPTO_REGS_KEY_0_WIDTH 32
