#
# Copyright (c) 2015 University of Cambridge
# Copyright (c) 2015 Noa Zilberman, Georgina Kalogeridou
# All rights reserved.
#
#  File:
#        Makefile
#
#
#  Description:
#        This makefile is used to generate and clean tools
#
# This software was developed by the University of Cambridge Computer Laboratory 
# under EPSRC INTERNET Project EP/H040536/1, National Science Foundation under Grant No. CNS-0855268,
# and Defense Advanced Research Projects Agency (DARPA) and Air Force Research Laboratory (AFRL), 
# under contract FA8750-11-C-0249.
#
# @NETFPGA_LICENSE_HEADER_START@
#
# Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for
# additional information regarding copyright ownership.  NetFPGA licenses this
# file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#   http://www.netfpga-cic.org
#
# Unless required by applicable law or agreed to in writing, Work distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
# @NETFPGA_LICENSE_HEADER_END@
#
# Vivado Launch Script
################################################################################

all: clean

distclean: clean

clean:	
		rm -rfv *.*~;\
		rm -rfv scripts/*.pyc;\
		rm -rfv scripts/*.*~;\
		rm -rfv scripts/NFTest/*.pyc;\
		rm -rfv scripts/NFTest/*.*~;\
		rm -rfv scripts/NFTest/NFTest/*.pyc;\
		rm -rfv scripts/NFTest/NFTest/*.*~;\

